### ISSUE TITLE
textview screen size issue

### ISSUE THREAD

**Issue by sushant-jain** [sushant-jain/tic-tac-toe#1]

**Comment by karanjuneja1106** [comment]
@sushant-jain 
what is the exact issue??
Can you please explain

**Comment by sushant-jain** [comment]
@karanjuneja1106 the textview in activity_main.xml with id tvx cutsoff the screen in some screen sizes.

**Comment by karanjuneja1106** [comment]
@sushant-jain I'm on it

**Comment by karanjuneja1106** [comment]
@sushant-jain for what screen size is it problematic??

**Comment by sushant-jain** [comment]
@karanjuneja1106  it works for all 1080p 5.5inches phones :p and some other resolutions but is problamatic on others
